apiVersion: v1
kind: Service
metadata:
  name: node-demo-service
  labels:
    app: node-demo
spec:
  type: NodePort
  selector:
    app: node-demo
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
      protocol: TCP
